### PR TITLE
cacert.pem - revision 2016-04-20

### PR DESCRIPTION
**Pull request by JanPetterMG**
Downloaded: from https://curl.haxx.se/ca/cacert.pem
Permalink: https://curl.haxx.se/ca/cacert-2016-04-20.pem

### CODE REVIEW

**Comment by ravage84** [comment]
:+1: verified with a WinMerge comparison.

Link to https://curl.haxx.se/ca/cacert-2016-04-20.pem can be found on https://curl.haxx.se/docs/caextract.html

**Comment by Seldaek** [comment]
interestingly, I get a different diff when updating this.. will check this out again later :)

**Comment by JanPetterMG** [comment]
@Seldaek Might it be an encoding problem? Don't try copy paste, it probably won't work.

**Comment by Seldaek** [comment]
I doubt it's encoding if entire blocks of ASCII characters disappear :) But yeah I don't have time to dig into it now so I'll see some other time.

**Comment by janedbal** [comment]
This PR removes Equifax, will it break Google certs again? See https://github.com/composer/ca-bundle/issues/3

**Comment by Seldaek** [comment]
Yeah that's another thing we would need to double check.

**Comment by JanPetterMG** [comment]
@janedbal I'm unable to reproduce the google error from issue #3.

```php
$curl = curl_init('https://maps.googleapis.com');
curl_setopt_array($curl, [
    CURLOPT_SSL_VERIFYHOST => 2,
    CURLOPT_SSL_VERIFYPEER => true,
    CURLOPT_HEADER => false,
    CURLOPT_CAINFO => \Composer\CaBundle\CaBundle::getBundledCaBundlePath(),
    CURLOPT_RETURNTRANSFER => true,
]);
$result = curl_exec($curl);

if ($result === FALSE) {
    echo curl_error($curl);
}
```
Tested with these URLs
- https://maps.googleapis.com
- https://googleapis.com
- https://developers.google.com/maps/
- https://gcm-http.googleapis.com/gcm
- https://google.com

I also noticed that #3 was using ``CaBundle::getSystemCaRootBundlePath()``, could someone please explain why? How can we be sure it's a problem with the library bundled cacert.pem, when it uses the systems own bundle as 1st priority?
For issues, we should always verify using ``CaBundle::getBundledCaBundlePath()`. Always!

As far as I can see, #3 hasn't really been verified by anyone.

**Comment by JanPetterMG** [comment]
__How can I trust this library, at all, when the bundle is customized, just because of an unverified issue? and the official up-to-date ca-bundle are put on hold because of potential issues with weak Google certificates? It's absolutely ridiculous!__

**Comment by Seldaek** [comment]
The issue was verified in another project IIRC and the cert didn't come out
of nowhere it was in a previous version of the curl cabundle.. Of course it
would be best to update it and have proper tests verifying this, but right
now I'm on holidays so I'd appreciate some patience instead of ridiculously
entitled behavior. We are all just doing our best here.

**Comment by ravage84** [comment]
@Seldaek I think you are refering to https://github.com/cakephp/cakephp/pull/8608#issuecomment-209184634.

May be stop reading your GH notifications for a while :smirk_cat: 
http://slides.seld.be/?file=2014-11-27+Five+Weird+Tricks+to+Become+a+Better+Developer.html#49

Enjoy your holidays :palm_tree:

**Pull request closed without merging**
