### PR TITLE
Add curl.cainfo

### PR DESCRIPTION
**Pull request by xPaw**
https://www.php.net/manual/en/curl.configuration.php

Similar to `openssl.cafile`.

### CODE REVIEW

**Comment by Seldaek** [comment]
I'm not entirely sure why but this breaks the 5.3/5.4/5.5 builds, so I am not so inclined to merge it as is. Can you explain more why we'd need this? It looks to me like this is a rather deprecated way of setting the cafile.

**Comment by xPaw** [comment]
> I'm not entirely sure why but this breaks the 5.3/5.4/5.5 builds

I'm not sure that CI failure is related to this PR.

> Can you explain more why we'd need this?

I personally had php configured to set `curl.cainfo`, but not the openssl option, so composer was failing for me.

> It looks to me like this is a rather deprecated way of setting the cafile.

Is it? Do you have a link?

**Comment by Seldaek** [comment]
openssl.cafile/capath were added in 5.6, and as far as I know they are the preferred way to configure this since then.

And yes the build failure appears to be caused by the change, I triggered a new build on master and it worked fine.

**Comment by xPaw** [comment]
Fair enough, looking at php's source code it does check openssl.cafile first, and then falls back to curl.cainfo.

Travis failure is strange, it would suggest that Travis enviroment sets `curl.cainfo` to something unexpected?

**Comment by Seldaek** [comment]
Yeah I am not sure why it fails there and why only on those versions.. But it just makes me think maybe it's not a great idea to add this if there's a chance of regression, given nobody else asked for it in the many years this code has been in broad use.

**Pull request closed without merging**
